CREATE FUNCTION [dbo].[FN_ADGroupType]
(
	@groupType BIGINT,
	@GROUP_TYPE_BUILTIN_LOCAL_GROUP BIT =	0,
	@GROUP_TYPE_ACCOUNT_GROUP BIT =			0,
	@GROUP_TYPE_RESOURCE_GROUP BIT =		0,
	@GROUP_TYPE_UNIVERSAL_GROUP BIT =		0,
	@GROUP_TYPE_APP_BASIC_GROUP BIT =		0,
	@GROUP_TYPE_APP_QUERY_GROUP BIT =		0,
	@GROUP_TYPE_SECURITY_ENABLED BIT =		0

)
RETURNS BIT
As
-- ========================================================
-- Author:				Gregor Spyra
-- Created:				2025.07.03
-- Project:				Syntra
-- Description:			Delivers boolean indicating whether
--						ADGroup.groupType attribute stores given flag
-- ========================================================
BEGIN
	DECLARE
		@LGROUP_TYPE_BUILTIN_LOCAL_GROUP BIGINT =	0x00000001,
		@LGROUP_TYPE_ACCOUNT_GROUP BIGINT =			0x00000002,
		@LGROUP_TYPE_RESOURCE_GROUP BIGINT =		0x00000004,
		@LGROUP_TYPE_UNIVERSAL_GROUP BIGINT =		0x00000008,
		@LGROUP_TYPE_APP_BASIC_GROUP BIGINT =		0x00000010,
		@LGROUP_TYPE_APP_QUERY_GROUP BIGINT =		0x00000020,
		@LGROUP_TYPE_SECURITY_ENABLED BIGINT =		0x80000000;

	DECLARE
		@RESULT BIT = 1;

	IF @GROUP_TYPE_BUILTIN_LOCAL_GROUP = 1 AND @RESULT = 1
		SET @RESULT = IIF(@groupType & @LGROUP_TYPE_BUILTIN_LOCAL_GROUP = 0, 0, 1)
	IF @GROUP_TYPE_ACCOUNT_GROUP = 1 AND @RESULT = 1
		SET @RESULT = IIF(@groupType & @LGROUP_TYPE_ACCOUNT_GROUP = 0, 0, 1)
	IF @GROUP_TYPE_RESOURCE_GROUP = 1 AND @RESULT = 1
		SET @RESULT = IIF(@groupType & @LGROUP_TYPE_RESOURCE_GROUP = 0, 0, 1)
	IF @GROUP_TYPE_UNIVERSAL_GROUP = 1 AND @RESULT = 1
		SET @RESULT = IIF(@groupType & @LGROUP_TYPE_UNIVERSAL_GROUP = 0, 0, 1)
	IF @GROUP_TYPE_APP_BASIC_GROUP = 1 AND @RESULT = 1
		SET @RESULT = IIF(@groupType & @LGROUP_TYPE_APP_BASIC_GROUP = 0, 0, 1)
	IF @GROUP_TYPE_APP_QUERY_GROUP = 1 AND @RESULT = 1
		SET @RESULT = IIF(@groupType & @LGROUP_TYPE_APP_QUERY_GROUP = 0, 0, 1)
	IF @GROUP_TYPE_SECURITY_ENABLED = 1 AND @RESULT = 1
		SET @RESULT = IIF(@groupType & @LGROUP_TYPE_SECURITY_ENABLED = 0, 0, 1)
	RETURN
		@RESULT
END
