<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PenguinConverters.Syntra.Consumer.SchemaDesigner</RootNamespace>
    <AssemblyName>PenguinConverters.Syntra.Consumer.SchemaDesigner</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PenguinConverters.Syntra.Core\PenguinConverters.Syntra.Core\PenguinConverters.Syntra.Core.csproj" />
  </ItemGroup>

</Project>
