<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PenguinConverters.Syntra.Provider.Infoblox</RootNamespace>
    <AssemblyName>PenguinConverters.Syntra.Provider.Infoblox</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Authors>Syntra Team</Authors>
    <Company>Penguin Converters AG</Company>
    <Product>Syntra</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PenguinConverters.Syntra.Core\PenguinConverters.Syntra.Core\PenguinConverters.Syntra.Core.csproj" />
  </ItemGroup>

</Project>
