<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>PenguinConverters.Syntra.Provider.Tenable</RootNamespace>
    <AssemblyName>PenguinConverters.Syntra.Provider.Tenable</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Authors>Syntra Team</Authors>
    <Company>Penguin Converters AG</Company>
    <Product>Syntra</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

</Project>
